Update eksperiment

diff --git a/eksperiment b/eksperiment
--- a/eksperiment
+++ b/eksperiment
@@ -29,6 +29,16 @@ city_data=$(cities_list)
 #Checking if the strin "city_data" is empty using "-z" 
 if [[ -z "$city_data" ]]; then
     #If the string is empty, then we print out this message and exits the script
+    echo "Failed to fetch city data. You are now exiting the game"
+    #exiting the script and using "1" to indicate that the script did not run successfully (if te script ran successfully, we would have used 0)
+    exit 1
+fi
+
+#making a variable and storing the information from the "cities_list" variable into this new one 
+city_data=$(cities_list)
+#Checking if the strin "city_data" is empty using "-z" 
+if [[ -z "$city_data" ]]; then
+    #If the string is empty, then we print out this message and exits the script
   echo "Failed to fetch city data. Exiting."
   exit 1
 fi
